name: CI

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  testing:
    name: Testing (${{matrix.package}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - utils
          - core
          - generator
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - run: pnpm i

      - run: pnpm build

      - run: pnpm test
        working-directory: packages/${{matrix.package}}
